<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $properties = [
            [
                'title' => 'Cozy Studio Apartment',
                'description' => 'A small yet comfortable studio perfect for students.',
                'main_image' => 'listing-1.jpg',
                'address' => 'Mannerheimintie 10',
                'gallery_images' => json_encode(['studio1_1.jpg', 'studio1_2.jpg']),
                'price' => 650.00,
                'available_from' => Carbon::now()->addDays(10)->toDateString(),
                'is_furnished' => true,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'zipcode' => '00100',
                'city' => 'Helsinki',
                'has_sauna' => false,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Spacious Two Bedroom Apartment',
                'description' => 'Great location with city views and modern amenities.',
                'main_image' => 'listing-2.jpg',
                'address' => 'Esplanadi 25',
                'gallery_images' => json_encode(['apt2_2.jpg', 'apt2_3.jpg', 'apt2_4.jpg']),
                'price' => 1200.00,
                'available_from' => Carbon::now()->addDays(5)->toDateString(),
                'is_furnished' => false,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'zipcode' => '00130',
                'city' => 'Helsinki',
                'has_sauna' => true,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Modern Apartment with Sauna',
                'description' => 'Enjoy the luxury of your own sauna in this modern apartment.',
                'main_image' => 'listing-3.jpg',
                'address' => 'Hämeenkatu 50',
                'gallery_images' => json_encode(['sauna_apt_1.jpg', 'sauna_apt_2.jpg']),
                'price' => 1350.00,
                'available_from' => Carbon::now()->addDays(15)->toDateString(),
                'is_furnished' => true,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'zipcode' => '33100',
                'city' => 'Tampere',
                'has_sauna' => true,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Affordable One Bedroom',
                'description' => 'Perfect for students, close to campus.',
                'main_image' => 'listing-4.jpg',
                'address' => 'Yliopistonkatu 7',
                'gallery_images' => json_encode(['affordable1_1.jpg']),
                'price' => 700.00,
                'available_from' => Carbon::now()->addDays(3)->toDateString(),
                'is_furnished' => false,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'zipcode' => '40100',
                'city' => 'Jyväskylä',
                'has_sauna' => false,
                'has_laundry' => false,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Luxury Penthouse',
                'description' => 'Top floor penthouse with panoramic views.',
                'main_image' => 'listing-5.jpg',
                'address' => 'Merikatu 10',
                'gallery_images' => json_encode(['penthouse_1.jpg', 'penthouse_2.jpg', 'penthouse_3.jpg']),
                'price' => 2500.00,
                'available_from' => Carbon::now()->addDays(30)->toDateString(),
                'is_furnished' => true,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'zipcode' => '00150',
                'city' => 'Helsinki',
                'has_sauna' => true,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Family Home with Garden',
                'description' => 'Perfect for families with children, spacious garden included.',
                'main_image' => 'listing-6.jpg',
                'address' => 'Kaislakatu 22',
                'gallery_images' => json_encode(['family_home_1.jpg', 'family_home_2.jpg']),
                'price' => 1600.00,
                'available_from' => Carbon::now()->addDays(12)->toDateString(),
                'is_furnished' => false,
                'bedrooms' => 4,
                'bathrooms' => 2,
                'zipcode' => '90210',
                'city' => 'Oulu',
                'has_sauna' => true,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Compact Studio Near University',
                'description' => 'Affordable studio close to university campus.',
                'main_image' => 'image-1.jpg',
                'address' => '20520 Turku',
                'gallery_images' => json_encode(['studio2_1.jpg']),
                'price' => 600.00,
                'available_from' => Carbon::now()->addDays(1)->toDateString(),
                'is_furnished' => true,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'zipcode' => '20520',
                'city' => 'Turku',
                'has_sauna' => false,
                'has_laundry' => false,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'City Center One Bedroom',
                'description' => 'Close to all amenities and public transport.',
                'main_image' => 'image-2.jpg',
                'address' => '90100 Oulu',
                'gallery_images' => json_encode(['citycenter1_1.jpg', 'citycenter1_2.jpg']),
                'price' => 850.00,
                'available_from' => Carbon::now()->addDays(20)->toDateString(),
                'is_furnished' => false,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'zipcode' => '90100',
                'city' => 'Oulu',
                'has_sauna' => false,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Modern Loft Apartment',
                'description' => 'Spacious loft with modern design elements.',
                'main_image' => 'image-3.jpg',
                'address' => '33200 Tampere',
                'gallery_images' => json_encode(['loft1_1.jpg', 'loft1_2.jpg']),
                'price' => 1400.00,
                'available_from' => Carbon::now()->addDays(7)->toDateString(),
                'is_furnished' => true,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'zipcode' => '33200',
                'city' => 'Tampere',
                'has_sauna' => true,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Quiet Suburban Home',
                'description' => 'Ideal for those seeking peace outside the city.',
                'main_image' => 'image-4.jpg',
                'address' => '02700 Espoo',
                'gallery_images' => json_encode(['suburban_home_1.jpg']),
                'price' => 1100.00,
                'available_from' => Carbon::now()->addDays(14)->toDateString(),
                'is_furnished' => false,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'zipcode' => '02700',
                'city' => 'Espoo',
                'has_sauna' => true,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Small Apartment with Balcony',
                'description' => 'Enjoy the fresh air on your private balcony.',
                'main_image' => 'image-5.jpg',
                'address' => '20100 Turku',
                'gallery_images' => json_encode(['balcony_apt_1.jpg', 'balcony_apt_2.jpg']),
                'price' => 900.00,
                'available_from' => Carbon::now()->addDays(9)->toDateString(),
                'is_furnished' => true,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'zipcode' => '20100',
                'city' => 'Turku',
                'has_sauna' => false,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Large Family Apartment',
                'description' => 'Spacious apartment suitable for large families.',
                'main_image' => 'image-6.jpg',
                'address' => '33100 Tampere',
                'gallery_images' => json_encode(['family_apt_1.jpg', 'family_apt_2.jpg']),
                'price' => 1700.00,
                'available_from' => Carbon::now()->addDays(25)->toDateString(),
                'is_furnished' => false,
                'bedrooms' => 4,
                'bathrooms' => 2,
                'zipcode' => '33100',
                'city' => 'Tampere',
                'has_sauna' => true,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Downtown Studio',
                'description' => 'Compact studio apartment in the heart of the city.',
                'main_image' => 'image-7.jpg',
                'address' => '00100 Helsinki',
                'gallery_images' => json_encode(['downtown_studio_1.jpg']),
                'price' => 750.00,
                'available_from' => Carbon::now()->addDays(4)->toDateString(),
                'is_furnished' => true,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'zipcode' => '00100',
                'city' => 'Helsinki',
                'has_sauna' => false,
                'has_laundry' => false,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Charming Cottage',
                'description' => 'A cozy cottage perfect for a quiet lifestyle.',
                'main_image' => 'image-8.jpg',
                'address' => '90500 Oulu',
                'gallery_images' => json_encode(['cottage_1.jpg', 'cottage_2.jpg']),
                'price' => 1300.00,
                'available_from' => Carbon::now()->addDays(20)->toDateString(),
                'is_furnished' => false,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'zipcode' => '90500',
                'city' => 'Oulu',
                'has_sauna' => true,
                'has_laundry' => false,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Modern Flat Near City Park',
                'description' => 'Bright flat with a view of the nearby city park.',
                'main_image' => 'image-1.jpg',
                'address' => '00500 Helsinki',
                'gallery_images' => json_encode(['citypark_flat_1.jpg', 'citypark_flat_2.jpg']),
                'price' => 1150.00,
                'available_from' => Carbon::now()->addDays(8)->toDateString(),
                'is_furnished' => true,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'zipcode' => '00500',
                'city' => 'Helsinki',
                'has_sauna' => false,
                'has_laundry' => true,
                'landlord_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('properties')->insert($properties);
    }
}
